using System.IO;

namespace ClamHub.Core;

/// <summary>
/// Defines all paths of the portable folder layout relative to the EXE location.
/// Called from: App.xaml.cs (startup), ConfigManager, SettingsManager and later
/// from DaemonController, ScanEngine and LogManager.
/// </summary>
public static class AppPaths
{
    /// <summary>Folder that contains ClamAV-GUI.exe. Everything is relative to this.</summary>
    public static string BaseDir { get; } = AppContext.BaseDirectory.TrimEnd(Path.DirectorySeparatorChar);

    /// <summary>Folder with the portable ClamAV binaries (clamd.exe, clamscan.exe, ...).</summary>
    public static string ClamAvDir => Path.Combine(BaseDir, "ClamAV");

    /// <summary>Folder for the virus signature database used by freshclam and clamd.</summary>
    public static string DatabaseDir => Path.Combine(ClamAvDir, "database");

    /// <summary>Folder for all log files (scan logs, daemon log, update log).</summary>
    public static string LogsDir => Path.Combine(BaseDir, "Logs");

    /// <summary>Folder where infected files are moved when quarantine mode is used.</summary>
    public static string QuarantineDir => Path.Combine(BaseDir, "Quarantine");

    // ClamAV executables
    public static string ClamdExe => Path.Combine(ClamAvDir, "clamd.exe");
    public static string ClamdScanExe => Path.Combine(ClamAvDir, "clamdscan.exe");
    public static string ClamScanExe => Path.Combine(ClamAvDir, "clamscan.exe");
    public static string FreshClamExe => Path.Combine(ClamAvDir, "freshclam.exe");

    // Config files (auto generated by ConfigManager when missing)
    public static string FreshClamConf => Path.Combine(ClamAvDir, "freshclam.conf");
    public static string ClamdConf => Path.Combine(ClamAvDir, "clamd.conf");

    // GUI settings and log outputs
    public static string SettingsFile => Path.Combine(BaseDir, "settings.json");
    public static string ProfilesFile => Path.Combine(BaseDir, "profiles.json");
    public static string HistoryFile => Path.Combine(LogsDir, "history.json");
    public static string QuarantineIndexFile => Path.Combine(QuarantineDir, "quarantine.json");
    public static string ScanLogFile => Path.Combine(LogsDir, "clamd-scan.log");
    public static string ClamdLogFile => Path.Combine(LogsDir, "clamd.log");
    public static string FreshClamLogFile => Path.Combine(LogsDir, "freshclam.log");
    public static string InfectedFilesReport => Path.Combine(LogsDir, "INFECTED_FILES.txt");

    /// <summary>Application icon, shipped next to the EXE for the context menu entry.</summary>
    public static string IconFile => Path.Combine(BaseDir, "ClamHub.ico");

    /// <summary>
    /// Creates all required folders if they do not exist yet.
    /// Called from: App.xaml.cs on startup, before any other component runs.
    /// </summary>
    public static void EnsureDirectories()
    {
        Directory.CreateDirectory(ClamAvDir);
        Directory.CreateDirectory(DatabaseDir);
        Directory.CreateDirectory(LogsDir);
        Directory.CreateDirectory(QuarantineDir);
    }
}
