using System.IO;

namespace ClamHub.Core;

/// <summary>
/// Defines all paths of the portable folder layout relative to the EXE location.
/// Called from: App.xaml.cs (startup), ConfigManager, SettingsManager and later
/// from DaemonController, ScanEngine and LogManager.
/// </summary>
public static class AppPaths
{
    /// <summary>Folder that contains ClamHub.exe. Everything is relative to this.</summary>
    public static string BaseDir { get; } = AppContext.BaseDirectory.TrimEnd(Path.DirectorySeparatorChar);

    /// <summary>The ClamAV executables that must be present for the app to work.</summary>
    public static readonly string[] RequiredBinaries =
        { "clamd.exe", "clamscan.exe", "clamdscan.exe", "freshclam.exe" };

    private static string? _clamAvDir;

    /// <summary>The built-in default ClamAV folder, next to the EXE.</summary>
    public static string DefaultClamAvDir => Path.Combine(BaseDir, "ClamAV");

    /// <summary>
    /// Folder with the portable ClamAV binaries (clamd.exe, clamscan.exe, ...).
    /// Defaults to BaseDir\ClamAV but can be repointed to an existing ClamAV folder
    /// the user selected (persisted as settings.ClamAvPath, re-applied on startup).
    /// </summary>
    public static string ClamAvDir => _clamAvDir ?? DefaultClamAvDir;

    /// <summary>
    /// Repoints ClamAvDir (and everything derived from it) to the given folder, or
    /// back to the default BaseDir\ClamAV when null/empty. Called from:
    /// App.OnStartup (saved path) and MainWindow.LocateClamAvFolderAsync.
    /// </summary>
    public static void SetClamAvDir(string? path)
        => _clamAvDir = string.IsNullOrWhiteSpace(path)
            ? null
            : path!.TrimEnd(Path.DirectorySeparatorChar);

    /// <summary>True when ClamAvDir was repointed away from the default location.</summary>
    public static bool ClamAvDirIsCustom => _clamAvDir != null;

    /// <summary>
    /// True when the folder contains every required ClamAV executable. Used to
    /// validate a saved path or a folder the user picked. Called from:
    /// App.OnStartup and MainWindow.LocateClamAvFolderAsync.
    /// </summary>
    public static bool ContainsClamAvBinaries(string dir)
    {
        try { return RequiredBinaries.All(e => File.Exists(Path.Combine(dir, e))); }
        catch { return false; }
    }

    /// <summary>Folder for the virus signature database used by freshclam and clamd.</summary>
    public static string DatabaseDir => Path.Combine(ClamAvDir, "database");

    /// <summary>Folder for all log files (scan logs, daemon log, update log).</summary>
    public static string LogsDir => Path.Combine(BaseDir, "Logs");

    /// <summary>Folder where infected files are moved when quarantine mode is used.</summary>
    public static string QuarantineDir => Path.Combine(BaseDir, "Quarantine");

    // ClamAV executables
    public static string ClamdExe => Path.Combine(ClamAvDir, "clamd.exe");
    public static string ClamdScanExe => Path.Combine(ClamAvDir, "clamdscan.exe");
    public static string ClamScanExe => Path.Combine(ClamAvDir, "clamscan.exe");
    public static string FreshClamExe => Path.Combine(ClamAvDir, "freshclam.exe");

    /// <summary>ClamAV configuration/diagnostics tool. Optional (not in RequiredBinaries).</summary>
    public static string ClamConfExe => Path.Combine(ClamAvDir, "clamconf.exe");

    // Config files (auto generated by ConfigManager when missing)
    public static string FreshClamConf => Path.Combine(ClamAvDir, "freshclam.conf");
    public static string ClamdConf => Path.Combine(ClamAvDir, "clamd.conf");

    // GUI settings and log outputs
    public static string SettingsFile => Path.Combine(BaseDir, "settings.json");
    public static string ProfilesFile => Path.Combine(BaseDir, "profiles.json");
    public static string HistoryFile => Path.Combine(LogsDir, "history.json");
    public static string QuarantineIndexFile => Path.Combine(QuarantineDir, "quarantine.json");
    public static string ScanLogFile => Path.Combine(LogsDir, "clamd-scan.log");
    public static string ClamdLogFile => Path.Combine(LogsDir, "clamd.log");
    public static string FreshClamLogFile => Path.Combine(LogsDir, "freshclam.log");
    public static string InfectedFilesReport => Path.Combine(LogsDir, "INFECTED_FILES.txt");

    /// <summary>Application icon, shipped next to the EXE for the context menu entry.</summary>
    public static string IconFile => Path.Combine(BaseDir, "ClamHub.ico");

    /// <summary>
    /// Creates all required folders if they do not exist yet.
    /// Called from: App.xaml.cs on startup, before any other component runs.
    /// </summary>
    public static void EnsureDirectories()
    {
        Directory.CreateDirectory(ClamAvDir);
        Directory.CreateDirectory(DatabaseDir);
        Directory.CreateDirectory(LogsDir);
        Directory.CreateDirectory(QuarantineDir);
    }
}
